github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
ports:
  - port: 3306
    onOpen: ignore
    visibility: private
  - port: 33060
    onOpen: ignore
    visibility: private
  - port: 8001
    onOpen: ignore
    visibility: public
image: pookmish/drupal8ci:gitpod
checkoutLocation: soe_profile
workspaceLocation: /workspace/stack
tasks:
  - before: >
      rm -rf ~/.ssh/id_rsa &&
      rm -rf ~/.ssh/id_rsa.pub &&
      eval $(command gp env -e) &&
      mkdir -p ~/.ssh &&
      [[ ! -z $SSH_PUBLIC_KEY  ]] &&
      echo $SSH_PUBLIC_KEY | base64 -d > ~/.ssh/id_rsa.pub &&
      chmod 644 ~/.ssh/id_rsa.pub &&
      [[ ! -z $SSH_PRIVATE_KEY  ]] &&
      echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa &&
      chmod 600 ~/.ssh/id_rsa &&
      [[ ! -z $GITCONFIG  ]] &&
      echo $GITCONFIG | base64 -d > ~/.gitconfig &&
      chmod 644 ~/.gitconfig
    init: >
      cd $GITPOD_REPO_ROOT &&
      export PROFILE_BRANCH=`git rev-parse --abbrev-ref HEAD` &&
      export PREVIEW_FULL_URL=`gp url 8001` &&
      export PREVIEW_URL=${PREVIEW_FULL_URL#"https://"} &&

      cd /workspace &&
      git clone https://github.com/SU-SWS/acsf-cardinalsites-public.git stack &&
      cd /workspace/stack &&
      rm -rf .git* &&

      composer remove su-sws/stanford_profile --no-update &&
      composer require su-sws/soe_profile:"dev-$PROFILE_BRANCH || $PROFILE_BRANCH-dev" --no-update &&
      composer update --no-interaction &&
      rm -rf docroot/*/custom/* &&
      composer install --prefer-source --no-interaction &&

      rm -rf docroot/profiles/custom/soe_profile &&
      rsync -r $GITPOD_REPO_ROOT docroot/profiles/custom/soe_profile &&

      cp .gitpod/blt.yml blt/local.blt.yml &&
      mkdir -p docroot/sites/settings &&
      cp .gitpod/global.settings.php docroot/sites/settings/global.settings.php &&
      find docroot/sites/ -name 'local*' | xargs rm &&
      blt blt:telemetry:disable --no-interaction &&
      blt settings &&
#      drush si soe_profile -v -y
#      drush cr
#      drush cim -y
#    command: |
#      apache2ctl restart
#      drush uli
#      drush uli | xargs gp preview --external
#      git config core.fileMode false
#      blt blt:telemetry:disable --no-interaction
#      git remote set-url origin git@github.com:SU-SWS/acsf-cardinalsites-public.git
