<?php

/**
 * @file
 * File description.
 *
 * Long description.
 */

/**
 * Implements hook_page_attachments().
 */
function soe_paragraphs_page_attachments(array &$page) {

  // Uncomment to add a library to all pages. It is recommended that you don't
  // just add a library to all pages but rather, conditionally require this
  // library only where it is needed.
  // See: https://www.drupal.org/node/2274843
  // $page['#attached']['library'][] = 'soe_paragraphs/soe_paragraphs';
}
