<?php

/**
 * @file
 * Preprocess functions for SOE Basic.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Prepares variables for the html.html.twig template.
 */
function soe_basic_preprocess_html(&$variables) {
  $variables['stanford_basic_path'] = \Drupal::service('extension.list.theme')
    ->getPath('stanford_basic');
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function soe_basic_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (!empty($variables['elements']['#id']) && $variables['elements']['#id'] == 'soe_basic_search') {
    $suggestions[] = 'block__stanford_basic_search';
  }
}

/**
 * Implements hook_preprocess_ds_entity_view().
 */
function soe_basic_preprocess_ds_entity_view(&$variables) {
  // Check if we have a valid entity.
  if (empty($variables['content']['#entity']) || !($variables['content']['#entity'] instanceof ContentEntityInterface)) {
    return;
  }
  
  $entity = $variables['content']['#entity'];
  
  // Check if this is a paragraph entity of the stanford_page_title_banner type.
  if ($entity->getEntityTypeId() !== 'paragraph' || $entity->bundle() !== 'stanford_page_title_banner') {
    return;
  }
  
  // Get the banner style from the react behaviors.
  $banner_style = $entity->getBehaviorSetting('react_paragraphs:page_title_variant_info', 'banner_style');
  
  // Add the banner style class to the wrapper if it exists.
  if (!empty($banner_style)) {
    $variables['attributes']['class'][] = $banner_style;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */

function soe_basic_preprocess_pattern_localfooter(&$variables) {
  $med = theme_get_setting('show_su_med_logo');
  $soe_basic_path = base_path() . \Drupal::service('extension.list.theme')
      ->getPath('soe_basic');

  // Default to Engineering.
  if (
    empty($variables['line1'])
    && (!isset($variables['custom_lockup']) || !$variables['custom_lockup'])
  ) {
    $variables['custom_lockup'] = 1;
    $variables['lockup_option'] = "su-lockup--option-a";
    $variables['line1'] = t('ENGINEERING');
    $variables['link'] = "https://engineering.stanford.edu/";
  }

  if ($med) {
    $variables['headercontent']['med_logo'] = [
      '#markup' => '
      <div class="su-med-logo">
        <a href="https://med.stanford.edu/">
          <img src="' . $soe_basic_path . '/src/assets/img/stanford_medicine.png" alt="Stanford Medicine home" />
        </a>
      </div>',
    ];
  }
}
